aws:
  account: "647309936627"
  region: us-west-1
resource_ids:
  pipeline_stack_id: GenericPipelineStack
  repo_code_asset_id: GenericCodeAsset
  repo_id: GenericRepo
  pipeline_id: GenericPipeline
  pipeline_stage_id: GenericStage
resources_names:
  repo_name: GenericRepo

