# Application config file
aws:
  account: # Account Number (Defaults to current CLI account)
  region: # Region (Defaults to current CLI region)
resource_ids:
  pipeline_stack_id: GenericPipelineStack # Stack ID for Pipeline Stack
  repo_code_asset_id: GenericCodeAsset # Stack ID for Code uploaded to repo.
  repo_id: GenericRepo # Stack ID for Repository
  pipeline_id: GenericPipeline # Stack ID for Pipeline
  pipeline_stage_id: GenericDeployStage # Stack ID for Deploy Stage of Pipeline
  stack_id: GenericStack # Stack ID for Resources Stack
resource_names:
  repo_name: GenericRepo # Repository Name
conditions:
  CREATE_REPO: false # Boolean for Repository Creation (Default false)
